name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - master
      - lecture*
      - homework*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '14.0.2'
      - name: assemble
        run: ./gradlew assemble
        working-directory: ./homework02
      - name: check DI module
        run: ./gradlew :di:check
      - name: check Webserver module
        run: ./gradlew :webserver:check
        working-directory: ./homework02

